version: '3'
services:
  front:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: react-container
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-network
    volumes:
      - ./client:/app
    depends_on:
      - server
  
  server:
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: node-container
    networks: 
      - mern-stack-network
    volumes:
      - ./server:/app
    depends_on:
      - mongo
  
  mongo :
    image: mongo   
    ports:
      - 27017:27017
    container_name: mongo-container
    networks:
      - mern-stack-network
    volumes:
      - mongoData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=talentelgiaCMS

networks:
  mern-stack-network:
volumes:
  mongoData:

